# Faster container-based infrastructure
sudo: false

language: python

# Python versions supported by channel's supported Django versions
python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -e .
  # Useful for debugging
  - pip freeze

script: python -m unittest discover
